language: python

python:
	- "2.6"
	- "2.7"
	- "3.3"
	- "3.4"

script:
	- python setup.py

after_success:
	- pip install coveralls
	- coverage run --source=tsutil setup.py
	- coveralls

notifications:
	email: false